//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LENHKHOP
    {
        public int IDKHOP { get; set; }
        public System.DateTime NGAYKHOP { get; set; }
        public int SOLUONGKHOP { get; set; }
        public double GIAKHOP { get; set; }
        public int IDLENHDAT { get; set; }
    
        public virtual LENHDAT LENHDAT { get; set; }
    }
}
