//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CKEntities : DbContext
    {
        public CKEntities()
            : base("name=CKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LENHDAT> LENHDAT { get; set; }
        public virtual DbSet<LENHKHOP> LENHKHOP { get; set; }
    
        public virtual int CursorLoaiGD(ObjectParameter outCrsr, string macp, string ngay, string loaiGD)
        {
            var macpParameter = macp != null ?
                new ObjectParameter("macp", macp) :
                new ObjectParameter("macp", typeof(string));
    
            var ngayParameter = ngay != null ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(string));
    
            var loaiGDParameter = loaiGD != null ?
                new ObjectParameter("LoaiGD", loaiGD) :
                new ObjectParameter("LoaiGD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CursorLoaiGD", outCrsr, macpParameter, ngayParameter, loaiGDParameter);
        }
    
        public virtual int SP_KHOPLENH_LO(string macp, string ngay, string loaiGD, Nullable<int> soluongMB, Nullable<double> giadatMB)
        {
            var macpParameter = macp != null ?
                new ObjectParameter("macp", macp) :
                new ObjectParameter("macp", typeof(string));
    
            var ngayParameter = ngay != null ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(string));
    
            var loaiGDParameter = loaiGD != null ?
                new ObjectParameter("LoaiGD", loaiGD) :
                new ObjectParameter("LoaiGD", typeof(string));
    
            var soluongMBParameter = soluongMB.HasValue ?
                new ObjectParameter("soluongMB", soluongMB) :
                new ObjectParameter("soluongMB", typeof(int));
    
            var giadatMBParameter = giadatMB.HasValue ?
                new ObjectParameter("giadatMB", giadatMB) :
                new ObjectParameter("giadatMB", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_KHOPLENH_LO", macpParameter, ngayParameter, loaiGDParameter, soluongMBParameter, giadatMBParameter);
        }
    
        public virtual ObjectResult<LENHDAT> SP_KHOPLENH_LO1(string macp, string ngay, string loaiGD, Nullable<int> soluongMB, Nullable<double> giadatMB)
        {
            var macpParameter = macp != null ?
                new ObjectParameter("macp", macp) :
                new ObjectParameter("macp", typeof(string));
    
            var ngayParameter = ngay != null ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(string));
    
            var loaiGDParameter = loaiGD != null ?
                new ObjectParameter("LoaiGD", loaiGD) :
                new ObjectParameter("LoaiGD", typeof(string));
    
            var soluongMBParameter = soluongMB.HasValue ?
                new ObjectParameter("soluongMB", soluongMB) :
                new ObjectParameter("soluongMB", typeof(int));
    
            var giadatMBParameter = giadatMB.HasValue ?
                new ObjectParameter("giadatMB", giadatMB) :
                new ObjectParameter("giadatMB", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LENHDAT>("SP_KHOPLENH_LO1", macpParameter, ngayParameter, loaiGDParameter, soluongMBParameter, giadatMBParameter);
        }
    
        public virtual ObjectResult<LENHDAT> SP_KHOPLENH_LO1(string macp, string ngay, string loaiGD, Nullable<int> soluongMB, Nullable<double> giadatMB, MergeOption mergeOption)
        {
            var macpParameter = macp != null ?
                new ObjectParameter("macp", macp) :
                new ObjectParameter("macp", typeof(string));
    
            var ngayParameter = ngay != null ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(string));
    
            var loaiGDParameter = loaiGD != null ?
                new ObjectParameter("LoaiGD", loaiGD) :
                new ObjectParameter("LoaiGD", typeof(string));
    
            var soluongMBParameter = soluongMB.HasValue ?
                new ObjectParameter("soluongMB", soluongMB) :
                new ObjectParameter("soluongMB", typeof(int));
    
            var giadatMBParameter = giadatMB.HasValue ?
                new ObjectParameter("giadatMB", giadatMB) :
                new ObjectParameter("giadatMB", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LENHDAT>("SP_KHOPLENH_LO1", mergeOption, macpParameter, ngayParameter, loaiGDParameter, soluongMBParameter, giadatMBParameter);
        }
    }
}
